Train:
  batch_size: 32
  learning_rate: 0.5
  reg: 0.0002
  epochs: 50
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet